---
- name: 'install'
  yum:
    name: 'iptables-services'
    state: 'present'
  notify: 'iptables clean rules'

- name: 'folders create'
  file:
      dest: '/root/scripts/iptables'
      owner: 'root'
      group: 'root'
      mode: '0700'
      state: 'directory'
      recurse: 'yes'

- name: 'scripts copy'
  template:
    src: 'scripts/iptables/{{ item }}.j2'
    dest: '/root/scripts/iptables/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0700'
  with_items:
    - 'iptables_setup.sh'
    - 'iptables_clean.sh'
    - 'ssh_open.sh'
    - 'ssh_close.sh'

- name: 'config'
  raw: '/root/scripts/iptables/iptables_setup.sh;/root/scripts/iptables/ssh_open.sh'

- name: 'startup'
  service:
    name: 'iptables'
    state: 'started'
    enabled: 'yes'
